"""empty message

Revision ID: 7db6569c00f1
Revises: 0841ca294cee
Create Date: 2023-11-22 11:08:43.674857

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7db6569c00f1'
down_revision = '0841ca294cee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location', sa.String(), nullable=False))
        batch_op.drop_column('zipcode')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('zipcode', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.drop_column('location')

    # ### end Alembic commands ###
